### ISSUE TITLE
Saving animation to file is slow

### ISSUE THREAD

**Issue by simonthor** [Zigolox/particle-system-simulation#2]
# Problem
Det tar **väldigt** lång tid för animationen att sparas som en fil. Tiden att rendera videon och extrahera all data från txt-filer till RAM är försumbar. 

# @simonthor s uppgifter
- [x] Ta reda på om det går att göra det snabbare.
- [x] Implementera denna feature.

**Comment by Zigolox** [comment]
Vilken Simon ska göra det? Använd @simonthor eller @Zigolox för att visa vem det är.

**Comment by simonthor** [comment]
Bra poäng. Ändrade i Issuen.

/Simon

________________________________
Från: Simon <notifications@github.com>
Skickat: Wednesday, September 18, 2019 9:16:10 PM
Till: Zigolox/particle-system-simulation <particle-system-simulation@noreply.github.com>
Kopia: simonthor <simon11.thor@hotmail.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Zigolox/particle-system-simulation] Saving animation to file is slow (#2)


Vilken Simon ska göra det? Använd @simonthor<https://github.com/simonthor> eller @Zigolox<https://github.com/Zigolox> för att visa vem det är.

**Comment by Zigolox** [comment]
This should be done soon!

**Comment by simonthor** [comment]
I will do it soon (maybe during the weekend), I just have to fix my space quiz first.

/Simon

________________________________
Från: Simon <notifications@github.com>
Skickat: Friday, September 20, 2019 1:20:13 PM
Till: Zigolox/particle-system-simulation <particle-system-simulation@noreply.github.com>
Kopia: simonthor <simon11.thor@hotmail.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Zigolox/particle-system-simulation] Saving animation to file is slow (#2)


This should be done soon!

**Comment by Zigolox** [comment]
Will it be done during this week? Maybe today?

**Comment by Zigolox** [comment]
This should really be fixed this weekend

**Comment by simonthor** [comment]
> This should really be fixed this weekend

Det var mycket svårare än jag trodde det skulle vara men jag jobbar på det

**Comment by simonthor** [comment]
Nu sparas en video med 100 frames, 1000 partiklar på 2.7 sekunder istället för 40 sekunder. Ska kolla om jag kan optimera den lite till men det är mycket bättre i alla fall.
